### PR TITLE
DRU proposals

### PR DESCRIPTION
**Pull request by iassael**
Hi Minqi, here are some minor changes in the DRU implementation, thoughts?

### CODE REVIEW

**Comment by minqi** [comment]
That looks good to me.

**Comment by minqi** [comment]
It looks like DIAL learns slightly more slowly when using sign() to discretize. I'm running 20 trials across 5000 epochs to compare. Will update this thread once I have the results.

**Comment by minqi** [comment]
It seems that discretizing using sign() leads to slower learning and a bit more variance in the rewards. A comparison is attached, averaged over 10 trials. I switched back to using sigmoid to discretize, but kept the other changes from this PR.
dial_sign_comp

**Comment by iassael** [comment]
This must be because the network has seen more values close to that. The hypothesis thought  is that the channel is discreet during deployment.

**Comment by minqi** [comment]
In that case, should we change to using sign()? The approach of discretizing as sigmoid(x*C) where C is a large multiplier effectively makes the channel discrete (e.g. values end up either at 2e-9 or 1) and seems to perform slightly better. This was also the same approach taken in the Lua codebase.

**Comment by iassael** [comment]
You are right, the difference was that it was constant 2 * 20, not 2 * 20 * sigma. The latter could make it not be close to 1. We could keep it as it was without the sigma, and do something similar for softmax.

**Comment by minqi** [comment]
That sounds good. I just created a PR implementing this and which also adds a config flag for setting hard vs soft discretization.

**Comment by iassael** [comment]
That's awesome, thanks!

**Comment by minqi** [comment]
👍

**Pull request merged**
